### ISSUE TITLE
Are there any quality guidelines here?

### ISSUE THREAD

**Issue by squinkylabs** [sfzinstruments/mappings#2]
Say, for example, I were to use a translator program to make some mappings that are perhaps "second rate", but might be useful to people. For example, most of the piano book library isn't translated.

Would it be appropriate to post mechanical translations here, or it this repo only for very high quality, hand-tuned mappings?

**Comment by kinwie** [comment]
I think anything that are correctly playable should be fine even if it auto converted. Most of my mappings here are hand-made just because I'm too used to do like that.

So if you want to contribute anything nice, please go ahead with any method you prefer. You still can update the sfz program later if you feel needed.

**Comment by squinkylabs** [comment]
thanks!
